### ISSUE TITLE
way to set executionPolicy+timeoutPolicy

### ISSUE THREAD

**Issue by mlin** [dnanexus/dxWDL#101]
Non blocker:

There are now large enough workloads running through dxWDL-compiled workflows that we have started to see the occasional random failure due to hardware flakeouts, cosmic rays, etc.
There should be some way (perhaps just a command-line option to the compiler for now) to set the DNAnexus executionPolicy and timeoutPolicy on the compiled applets.

**Comment by orodeh** [comment]
Supported in version 0.65: 
https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#setting-dnanexus-specific-attributes-for-tasks
