### ISSUE TITLE
setting access for applets

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dxWDL#106]
It would be good if one could set the network and project access criteria for applets generated by dxWDL.  Right now it seems that the applets get full network access, which is great, but that's a non-documented feature, so I feel uneasy relying on it.  It would be better if the access could be specified either in the WDL file in the runtime section, or through dxWDL parameters.

**Comment by orodeh** [comment]
This will be supported in release 0.65, which is planned for this week.

**Comment by orodeh** [comment]
Please check this section for instructions: https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#setting-dnanexus-specific-attributes-for-tasks

**Comment by notestaff** [comment]
@orodeh thanks a lot!
