### ISSUE TITLE
streaming between stages

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dxWDL#109]
If one could mark not just input files but also output files with parameter_meta: "stream", then you could identify groups of workflow stages that can be run in parallel, rather than sequentially, by streaming the output of one stage into the next.  You'd then combine these stages into a single stage of the resulting workflow, where the stages' commands are run in parallel and results are streamed between original stage implementations through named pipes.

**Comment by orodeh** [comment]
Allowing output files to be streamed is a useful feature. Several users, internal and external, have asked for it. Marking it as "enhancement".

**Comment by orodeh** [comment]
I don't see this getting implemented.
