### ISSUE TITLE
using the word "last" in names of variables or tasks produces error

### ISSUE THREAD

**Issue by lltw** [dnanexus/dxWDL#137]
Hello!
While trying to compile the WDL workflow utlizing the program [Samblaster](https://github.com/GregoryFaust/samblaster) I have noticed a minor, but confusing bug. It seems that if the name of a variable or a task contains the string "last", dxWDL throws "Illegal variable name" or "Illegal call name" error while compiling. The placement of the string "last" within name seems to be irrelevant.

For example, the following workflow compiles just fine:

```
workflow Hello {

  String name = "Jane"
  
  call SayHelloPolitely {
    input: 
      name = name
  }
  output {
    String output_string = SayHelloPolitely.output_string 
  }  
}

task SayHelloPolitely {
  String name
  
  command <<<
    echo "Hello, ${name}!"
  >>>
  
  output {
    String output_string  = "Nice to see you, ${name}!"
  }
}
```

but when changed to:

```
workflow Hello {

  String last_name = "Jane"
  
  call SayHellastloPolitely {
    input: 
      name = last_name
  }
  output {
    String output_string = SayHellastloPolitely.output_string 
  }  
}

task SayHellastloPolitely {
  String name
  
  command <<<
    echo "Hello, ${name}!"
  >>>
  
  output {
    String output_string  = "Nice to see you, ${name}!"
  }
}
```

produces an error:

```
Namespace validation error

java.lang.RuntimeException: Illegal variable name

hello.wdl, line 3
  String last_name = "Jane"
         ^


Illegal call name SayHellastloPolitely

hello.wdl, line 5
  call SayHellastloPolitely {
       ^

```

The workflows run normally when executed by [Cromwell](https://github.com/broadinstitute/cromwell), those errors are produced only when compiling with dxWDL. While the problem is minor, it may cause the potential user to spend a lot of time figuring out why the innocent variable/task names (like BwaMemAndSamblaster) cause trouble.

**Comment by orodeh** [comment]
Thanks for the report, this is now fixed in master.
