### ISSUE TITLE
Default input values not honored in subworkflow

### ISSUE THREAD

**Issue by mlin** [dnanexus/dxWDL#141]
**outer.wdl:**
```
import "hello.wdl" as hello

workflow outer {
    String? who
    call hello.wf { input:
        who = who
    }
}
```

**hello.wdl variant 1:**

```
workflow wf {
    String? who

    call hello { input:
        who = who
    }
}

task hello {
    String? who = "world"

    command {
        echo "Hello, ${who}"
    }
}
```

**hello.wdl variant 2:**
```
workflow wf {
    String? who = "world"

    call hello { input:
        who = who
    }
}

task hello {
    String who

    command {
        echo "Hello, ${who}"
    }
}
```

**Issue:**

If we build this with dxWDL v0.66.2 and `dx run outer -y`, with variant 1, everything runs but `who` is an empty string at runtime (!). With variant 2, the job fails with `InputError: i/o value who is not a string`

This only happens when `hello.wf` is called as a subworkflow. If we compile and run it directly both variants seem to work as expected.

**Comment by orodeh** [comment]
variant 1: 
1) reported a [Cromwell issue](https://github.com/broadinstitute/cromwell/issues/3819).
2) Added a markdown page (doc/Howto.md) that shows a worked solution.
 
I could not reproduce variant 2.

**Comment by orodeh** [comment]
The test case I have now matches the Cromwell behavior, which I think is arguably correct. 

```
workflow call_with_defaults2 {
    String? who

    call username as u1 { input: who = who }
    call username as u2
    call username as u3 { input: who = "Sandy" }

    output {
        String r1 = u1.result
        String r2 = u2.result
        String r3 = u3.result
    }
}

task username {
    String? who = "world"

    command {
        echo "Hello, ${who}"
    }
    output {
        String result = read_string(stdout())
    }
}
```

The results are the same between Cromwell and dxWDL:
```
{
  "call_with_defaults2.r1" : "Hello, world",
  "call_with_defaults2.r2" : "Hello, world",
  "call_with_defaults2.r3" : "Hello, Sandy"
}
```
