### ISSUE TITLE
Support for WDL 1.0

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/dxWDL#150]
**Request:**
The WDL language spec has reached v1.0. It would be helpful for `dxWDL` to support [WDL format 1.0](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) rather than or in addition to [draft-2](https://github.com/openwdl/wdl/blob/master/versions/draft-2/SPEC.md) format.

**Background:**
We have a series of [WDL workflows](https://github.com/broadinstitute/viral-ngs/tree/master/pipes/WDL) as part of our toolkit for viral genome assembly and analysis. We would like to port these to WDL 1.0 so we can use the latest versions of [cromwell](https://github.com/broadinstitute/cromwell) for testing, validation, and local execution. We have a standing issue to update the workflows to WDL 1.0 format: https://github.com/broadinstitute/viral-ngs/issues/837, however resolution is currently blocked as WDL 1.0 is not yet supported by dxWDL.

**Comment by dpark01** [comment]
Also keep in mind that WDL 1.0 has a [different way](http://cromwell.readthedocs.io/en/develop/optimizations/FileLocalization/) of handling non-localized file inputs in `parameter_meta` than how dxWDL does it.

**Comment by orodeh** [comment]
I looked at it, and supporting WDL 1.0 is not going be simple. dxWDL uses the cromwell-wdl library, previously known as [wdl4s](https://github.com/broadinstitute/wdl4s). Between draft-2 and version 1.0, wdl4s was absorbed into Cromwell and largely rewritten. The external facing documentation does not exist anymore.

**Comment by dpark01** [comment]
Uh.. that seems like a bug (either for Cromwell or for OpenWDL, depending where the fuzzy line of responsibility falls).

**Comment by orodeh** [comment]
_Technically_ speaking, OpenWDL is a standard, separate from Cromwell. It is just that there is currently only a one parser for it, which is cromwell-wdl (at least, one that I know of). In theory, anyone can write their own parser.

One way or the other, it won't be easy.

**Comment by dpark01** [comment]
Right, what I meant was, is it an OpenWDL problem that no platform-independent parser exists for 1.0? Or was it always considered the Cromwell team's responsibility to provide that parser for everyone (in which case it's a Cromwell bug that it no longer does so for 1.0)? And if it is no longer considered their responsibility, perhaps a case needs to be made for either breaking off that component (the parser) into a separate non-Cromwell project again, or advocating for increasing the scope of their responsibility.

In terms of "who do I complain to", I know the answer involves the same individuals upstairs either way, the question is more about which hats they wear when I ask them / which github repo to file issues on. I can ask around, or we could just tag them here.

**Comment by orodeh** [comment]
It would be great to ask. The person I've been talking to is Christopher Llanwarne, who is the team lead for the language part of the Cromwell project. Note that wdl4s performed not just parsing, but also typing, and expression evaluation.

**Comment by orodeh** [comment]
Work in this is progressing in branch [wom_modern](https://github.com/dnanexus/dxWDL/tree/wom_modern).

**Comment by orodeh** [comment]
Version 1.00 now supports both draft-2 and version-1.0. Please give it a spin!

**Comment by tomkinsc** [comment]
Great, thanks so much! It may be a little while until we start updating our pipelines, but hopefully not too long.
