### ISSUE TITLE
Job error reporting

### ISSUE THREAD

**Issue by dpark01** [dnanexus/dxWDL#152]
Out of curiosity, is there a mechanism for the code within a WDL task to provide some descriptive string upon failure that gets somehow moved into a `job_error.json` file or otherwise gets reported on by the DNAnexus UI (instead of "Please consult the job log")? The native workflows seem to do something like [this](https://github.com/dnanexus/viral-ngs/blob/dnanexus/assembly/viral-ngs-assembly-scaffolding/src/code.sh#L36) but I'm wondering if there's a way to do that within a WDL instead. It's fine if the solution isn't feature-portable to Cromwell, et al (as long as it still compiles there).

**Comment by jtratner** [comment]
This would be a super useful feature. This came up as a potential limitation of using dxWDL.

**Comment by jtratner** [comment]
@dpark01 - this actually is already available (if you want to do something custom to the platform), you just have to write out to `job_error.json` in your home directory. 

```
workflow show_error {
    call make_error {}
}

task make_error {
    command <<<
        echo '{"error": {"type": "AppError", "message": "x must be at least 2"}}' > job_error.json
        exit 1
    >>>
}
```

**Comment by orodeh** [comment]
I like it 👍

**Comment by orodeh** [comment]
If you want to do something that is WDL compliant, you can do this (adapted from code by @mlin )
```bash
task assert {
    Boolean value
    String msg

    command {
        if [ "${value}" == "false" ]; then
            echo $msg
            exit 1
        fi
        exit 0
    }
}
```

**Comment by orodeh** [comment]
I wrote this as a page in the documentation: https://github.com/dnanexus/dxWDL/blob/master/doc/Tips.md
