### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by vsoch** [dnanexus/dxWDL#155]
Instead of needing to install on the host, it would be great to have a Docker container provided for the user. Would this be possible?

**Comment by orodeh** [comment]
Can you please extend the description a little bit? Perhaps with an example for how you want to use this feature? What is the host where docker is installed?

**Comment by vsoch** [comment]
hey @orodeh ! How about I'll do a PR with a first shot instead? I'm working on it now ;)

**Comment by vsoch** [comment]
And to answer your question, I'm testing the pipelines here for DNAnexus and have a conversion I'd like to do, without installing things  on my host :) --> https://github.com/ENCODE-DCC/wdl-pipelines/blob/master/docs/install.rst#dnanexus-platform Stay tuned, I'll (hopefully) have something to start us off!

**Comment by orodeh** [comment]
@vsoch, sure a PR would be nice :-)  I think it isn't dxWDL that is requiring docker on your development machine though. It may be the ENCODE pipeline install sequence.

**Comment by vsoch** [comment]
oh Docker isn't a problem at all, I have that! You are correct that I'm interacting with DNAnexus and part of that is doing a conversion using the .jar in this repository. I'd rather interact with the jar via a container than need to do this on my host (that way others can just pull / use and be done!)

**Comment by vsoch** [comment]
And please excuse my naivety about the domain, I'm a noob and learning as I go :)
