### ISSUE TITLE
[docker] Automated deployment on Docker Hub?

### ISSUE THREAD

**Issue by vsoch** [dnanexus/dxWDL#157]
hey @orodeh me again! Before I forgot, I wanted to see if you wanted to create an automated deployment for the Dockerfile on Docker Hub? E.g., a container here --> https://hub.docker.com/u/dnanexus/ so a new user could just run:

```bash
docker run dnanexus/dxwdl ...
```
and be done! It looks like there are some good containers there already, and it would be good to get this one in too. I'm writing up docs for using the tool, and instead of my "vanessa dinosaur" container, it would be good to have the one built from here, in case there are future changes.

**Comment by orodeh** [comment]
@vsoch, I have my hands full with other things. However, you are welcome to the docker image; you can mention it from the readme if you want. Just make sure to own it, so that if someone uses your docker image, are runs into a problem, she will be able to ask for instructions.
