### ISSUE TITLE
Preserve folder hierarchies on the platform

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#168]
Right now, running a WDL workflow on the platform does not end up with any folder structure, which can get a little goofy if you have tons of files.  I'm wondering if it would be possible to upload to the container preserving the local folder structure, i.e. if I do:

```
command <<<
    touch alignments/1.bam
    touch alignments/2.bam
>>>
output { Array[File] alignments = glob("alignments/*.bam") }
```
Rather than dx upload to /, do a dx upload to `/alignments` (code-wise, I'm thinking this would only apply if you specified relative paths in the output field).  (and I believe this would mean that, if you specified a destination to the job, it'd become an `$DESTINATION/alignments` according to DNAnexus spec).

Currently, some folks are writing an applet to reorganize outputs into folders, which works but means writing a lot of boilerplate that's far from the DAG (and also means that you can't take advantage of it if you run one step or reuse a step in multiple workflows)

Given that the individual tasks really only care about file names (which are independent of folder structure), the input folder structure is supposed to be opaque and/or defined by input names, and all the references ought to be to dxIDs, would this be possible/reasonable to do?

**Comment by jtratner** [comment]
Maybe this could be implemented by changing [uploadFile](https://github.com/dnanexus/dxWDL/blob/aa1c699e6c74c819e94d84b96328abf486d9cc27/src/main/scala/dxWDL/Utils.scala#L564) to take in an optional root parameter and then to compute a target path relative to the root?  (I think this is always `/home/dnanexus` right now anyways)

In python this would look like:

```
from pathlib import Path
def compute_target_path(dest: Path, root: Path):
    default = Path(f'/{dest.name}')
    if not root:
        return default
    try:
        relpath = dest.relative_to(root)
        # force to absolute path
        return Path(f'/{relpath}')
    except ValueError:
        # root is not a parent of dest
        pass
    return default
P = Path
assert compute_target_path(P('/home/dnanexus/out/file.bam'), P('/home/dnanexus/out')) == P('/file.bam')
assert compute_target_path(P('/home/dnanexus/out/alignments/file.bam'), P('/home/dnanexus/out')) == P('/alignments/file.bam')
assert compute_target_path(P('/otherroot/alignments/file.bam'), P('/home/dnanexus')) == P('/file.bam')
assert compute_target_path(P('/otherroot/alignments/file.bam'), None) == P('/file.bam')
assert compute_target_path(P('/otherroot/alignments/file.bam'), '') == P('/file.bam')
```

and then dx upload command changes like this:

```diff
-val dxUploadCmd = s"dx upload ${path.toString} --brief"
+val dxUploadCmd = s"dx upload ${path.toString} --brief --destination=${computeTargetPath(path, root)}"
```

**Comment by jtratner** [comment]
One last point: what we really want is a clean way to specify output folders in the DAG. This seems like potentially a good way to do it, though it does introduce requirement to do things like:

```
mkdir calls
call-stuff --output calls/sample.vcf
```

within the DAG, so it might also increase the verbosity of task definitions.

Maybe another way to handle would be to specify it in the meta section?

**Comment by orodeh** [comment]
@jtratner, a unified handling of paths, WDL, and DNAx is not a simple thing. There are two things you can already do:
1. Use the --reorg flag
2. Specify the output folder for a DNAx workflow

A third option is to create a task at the end of the workflow, that does not use docker. It will run the default bash shell, allowing use of `dx upload` and `dx move` commands. That applet will require CONTRIBUTE access.

**Comment by orodeh** [comment]
Our plan is wait for WDL to support the `Directory` type.  Once the WDL issues are worked out, we can figure out how to get it to work on DNAx.

**Comment by jtratner** [comment]
Just to clarify one point: I’m not saying that we want to consider
directories of files together, we are just hoping to make it easier to
organize files afterward. (And keep the organization closer to the task
rather than having to keep a separate config in sync)

I wouldn’t expect the WDL pipeline to really have any sense of how files
are organized on DNAnexus (presumably they’d just be dealing with
pointers), I’m looking to impose a bit of organization for easier browsing.

Overall, this would be more about user convenience after the fact (and mean
we don’t have to develop a custom application each time to reorganize
outputs).

**Comment by odoublewen** [comment]
@orodeh Does the merge of https://github.com/openwdl/wdl/pull/241 mean that WDL now supports a `directory` type?   For those of us who are used to developing complex pipelines in the `dxworkflow.json` format, the lack of output file organization is a definite pain point.  Thanks.

**Comment by orodeh** [comment]
Very well, maybe it is time to go back to thinking about directories.

**Comment by jtratner** [comment]
@orodeh - Perhaps we can share our reorg app with you so you can take a look at how we've done it.  I think it'd be really helpful to have each run always dump to a subdirectory in some way.  It's been really really helpful to have some kind of default organization, even if not specified (especially because different steps of the pipeline can produce the same named file but it can have different meanings).  I'd *love* dxWDL to either preserve directory names on upload (e.g., some logic on how it uses dx upload relative to current directory) OR to allow some kind of meta parameter to specify which directory files should go.

Currently, we have a reorg app that runs post-analysis that re-organizes based upon regex matching on output name (see end for an example).

When an output or file isn't matched:

1. Intermediates go into a subdirectory called intermediates, and then in individual folders by output and stage name (e.g., `intermediates/stage-4.bcl2fastq220_reads2/` or `intermediates/stage-10.stage-5.some_assay__scatter_bam_body_logs1`)
2. Outputs go into a subdirectory called "unmatched_outputs" (e.g., `unmatched_outputs/metric_csvs`)

```
some_seq_assay:
  input_reorg:
  - regex: manifest
    directory: ./
  output_reorg:
  - regex: samplesheet
    directory: ./
  # alignments
  - regex: .*reads.*
    directory: alignments
  - regex: .*bais
    directory: alignments
  - regex: .*bams
    directory: alignments
  # metrics
  - regex: .*probe2pos_gene.*
    directory: metrics
  - regex: .*metrics.*
    directory: metrics
  # calls
  - regex: .*vcfs
    directory: calls
  - regex: .*beds
    directory: calls
  # plots
  - regex: .*plot.*
    directory: plots
```

**Comment by jtratner** [comment]
(if folder hierarchies were preserved, that'd cover 90% of what we'd want - tho we'd still want to move intermediates to a different folder)

**Comment by orodeh** [comment]
I think this is going to be passed to the professional services department, and they will decide, with you guys, what to do. 

Can we close the ticket?

**Comment by odoublewen** [comment]
@orodeh  Not sure what/who is the "professional services department" but closing this issue is your call, I suppose!

Just out of curiosity, this doesn't mean you're stepping away from dxWDL, does it?

**Comment by orodeh** [comment]
@odoublewen No, I am not stepping away from the project :-)

I am actually working on solving a piece of this problem, by supporting WDL style directories. This is strictly exploratory for now. 

The professional service group is a part of the dnanexus company which, I believe, is talking with Jeff about this and other issues you have.

**Comment by RachelDuffin** [comment]
Hi, I wanted to add that my team would also find this behaviour very useful. We are investigating switching over to WDL workflows and are almost there for one of our pipelines. However, one of the problems is that whilst the '--stage-relative-output-folder' argument allows specifying the relative output folder per task for all files produced by that task, it does not allow for individual files to be placed in different directories. It would be very helpful if the platform allowed for this behaviour through specification in the outputs section of each WDL task, rather than needing to create a separate reorg app (this just adds to the code base that needs to be maintained and means that files are only moved to the correct location at the end of the workflow rather than at the point of delocalisation). Many thanks!

Edit - apologies I just realised this issue is not in the dxCompiler repository; I will reopen the issue there.
