### ISSUE TITLE
Automatically convert DNAnexus arrays to WDL arrays

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#173]
Right now we are using a native applet for one part of our WDL workflow (to handle bcl2fastq).  I'm not sure if bug or intended, but dxWDL won't allow me to reference arrays of files that are outputted from that workflow as workflow outputs.  Would it be possible to automatically translate these arrays?

To get around this, I have a task like this:

```
task nativize_array {
    # handles converting an array into an output array (doesn't cause a copy)
    # s.t. dxWDL can re-use the outputs in a workflow output
    Array[File] in
    command {}
    output {
        Array[File] out = in
    }
}
```

with a bcl2fastq220 task like this:

```
task bcl2fastq220 {
    Array[File] run_archive
    File? sample_sheet
    Boolean no_lane_splitting
    String? advanced_opts
    command {
    }
    output {
        Array[File]+ stats = [""]
        Array[File]+ demux_summaries = [""]
        Array[File]+ fastq_summaries = [""]
        Array[File]+ reads = [""]
        Array[File] reads2 = []
    }
    meta {
        type: "native"
        id: "applet-<applet>"
    }
}
```

and then ultimately I do this in the workflow outputs:

```
    call nativize_array as b2q_stats {
        input: in=bcl2fastq220.stats
    }
    call nativize_array as b2q_demux_summaries {
        input: in=bcl2fastq220.demux_summaries
    }
    call nativize_array as b2q_fastq_summaries {
        input: in=bcl2fastq220.fastq_summaries
    }
   output {
        # bcl2fastq
        Array[File] bcl2fastq_stats = b2q_stats.out
        Array[File] bcl2fastq_demux_summaries = b2q_demux_summaries.out
        Array[File] bcl2fastq_fastq_summaries = b2q_fastq_summaries.out
}
```

**Comment by orodeh** [comment]
@jtratner, this may be because you cannot cast between `Array[File]` and `Array[File]+`.

`bcl2fastq220.demux_summaries` is of type `Array[File]+`, but the workflow output is of type `Array[File]`. If you change the types to match, you wouldn't need the `nativize_array` procedure.

**Comment by jtratner** [comment]
@orodeh - you're right - man I thought I'd tried that (might have been me trying 2/3 with Array[File]+) - sorry about the false alarm.
