### ISSUE TITLE
spaces in output file

### ISSUE THREAD

**Issue by ying-w** [dnanexus/dxWDL#181]
In my WDL file I have

```wdl
output { 
Array[File] output_plots = glob("*.pdf")
}
```

and the command will output a series of plots such as `figure 1.pdf` `figure 2.pdf` and `figure 3.pdf`

while its running on the platform, I get an IO error because it gets converted into

```bash
dx upload /home/dnanexus/figure 1.pdf --brief
```

The output file should be quoted to account for spaces in filename

**Comment by orodeh** [comment]
Fixed on master.
