### ISSUE TITLE
dnanexus/dxwdl image does not contain dx toolkit

### ISSUE THREAD

**Issue by mfojtak** [dnanexus/dxWDL#189]
dxwdl dockerfile installs toolkit in the first step but the actual dockerhub image doesn't have it.
It looks like the image is build using different dockerfile.

dxwd image becomes useless without ability to run dx login.

**Comment by orodeh** [comment]
@mfojtak, the [Dockerfile](https://github.com/dnanexus/dxWDL/blob/master/scripts/compiler_image/Dockerfile) doesn't install the dx-toolkit. You are not supposed to use the dx-toolkit inside the image, it just saves you the installation of java. 

From your bash command line you can do:
```bash
$ source environment
$ dx login
$ docker run dnanexus/dxwdl compile xxxx.wdl --project MY_PROJECT
```

This way, you don't need to install java, or the dxWDL jar file.

**Comment by orodeh** [comment]
@mfojtak, added documentation here: 
https://github.com/dnanexus/dxWDL#compiler-docker-image

**Comment by mfojtak** [comment]
@orodeh **You are not supposed to use the dx-toolkit inside the image**
Why not? Installation of dx toolkit is not worth automating? Has to be manual for some reason?

**Comment by orodeh** [comment]
@mfojtak  There is a different image you might want to use, in this case. It was created by @vsoch, https://github.com/dnanexus/dxWDL/tree/master/contrib/docker. 
It does have the dx-toolkit inside it. 

I didn't include the dx-toolkit, because it also hase

**Comment by orodeh** [comment]
@mfojtak, does this answer your question?
