### ISSUE TITLE
using expressions in subworkflow's output block

### ISSUE THREAD

**Issue by leepc12** [dnanexus/dxWDL#206]
Your test workflow WDLs (`trains.wdl` and `check_route.wdl`) work fine with `cromwell-38.jar`.
```
$ java -jar ~/cromwell-38.jar run trains.wdl -i trains_input.json
```

I would like to use `if` expressions in the output section of a subworkflow. This will be very helpful for my projects (ATAC/ChIP ENCODE pipelines) to selectively choose to run a task in a subworkflow.
```
workflow bowtie2 {
	File? fastq_R1
	File? fastq_R2

	Boolean need_to_run = ...

	if (need_to_run) {
		call bowtie2_ { input:
			fastq_R1 = fastq_R1,
			fastq_R2 = fastq_R2,
		}
	}

	output {
		File? bam = if need_to_run then bowtie2_.bam else ...
	}
}
```

The following [code](https://github.com/dnanexus/dxWDL/blob/e8523eb1f270426b7649a23c0830d9f76093d674/test/subworkflows/check_route.wdl#L19) is with a trivial expression in the output block. This works fine with `cromwell-38.jar` but not with `dxWDL-0.81.3`.
```
    output {
        Array[String] result = if true then concat2.result else []
    }
```

**Comment by orodeh** [comment]
Sure, this is implemented in the new compiler version, which isn't ready yet for prime time. 

Could you please request this feature through the management channels? It will require engineering time.

**Comment by leepc12** [comment]
Sure, I am happy to do that. How can I request it through the management channel?

**Comment by orodeh** [comment]
You can ask Seth to raise it as a user request/requirement with Geet.

**Comment by orodeh** [comment]
Version 1.00 supports this feature. Please try it, and let me know if it works as expected.

**Comment by orodeh** [comment]
Should work now. We can reopen if it doesn't.
