### ISSUE TITLE
Run scatter as many processes on one worker

### ISSUE THREAD

**Issue by krhaas** [dnanexus/dxWDL#209]
A feature idea: 

Allow running scatter stages as many processes on one box instead of many individual boxes.  This would help in instances where each task that the scatter called was relatively short (1-5 min) but required downloading large files (like hg19.fa). 

For example in an abridged version of the demo WDL file, if you had 1,000 small bams, it would be convenient to spin up only 1 box, download the genome and docker container once, then kick off many processes (ideally in parallel given number of cores). Otherwise you would have to incur the overhead of spinning up 1000 boxes and downloading genome and docker container 1000 times.

```wdl
workflow bam_chrom_counter {
    Array[File] bams
    File genome

    scatter (bam in bams) {
        call count_bam {
            input: bam = bam, genome=genome
            meta: "multi-processing"
        }
    }
    output {
        File bai = slice_bam.bai
        Int count = count_bam.count
    }
}

task count_bam {
    File bam
    File genome

    command <<<
        samtools view -c ${bam}
    >>>
    runtime {
        docker: "quay.io/ucsc_cgl/samtools"
    }
    output {
        Int count = read_int(stdout())
    }
}
```

**Comment by orodeh** [comment]
@krhaas, this an interesting feature request. The main challenge is that it is difficult to tell at compile time if tasks should be packed together on the same instance. Perhaps a runtime system could do this, I am not sure.

**Comment by jtratner** [comment]
In general, it's pretty easy for us to know ahead of time if it needs to be packed on to one node - perhaps the user could add an annotation in meta section?

Given that dxWDL runs in a container, seems like it'd be pretty easy to reset the container environment each time.

**Comment by orodeh** [comment]
I have difficulty seeing this issue being addressed the near future. The idea is solid, but I don't see it getting implemented. 

Sorry, 
     Ohad.
