### ISSUE TITLE
Unclear how to detect job ID within container -- running in native docker changes hostname

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#213]
Imagine I have a task like this:

```
task fail_with_message {
command <<<
        echo '{"error": {"type": "AppError", "message":"Hit failure in taskname ( '$(hostname)')"}}' > job_error.json
        exit 1
>>>
}
```

It's useful because the apperror you get (with dx-docker version) looks like `Hit failure in taskname (job-123)`.  This is super helpful because sometimes the platform identifies the wrong job as the root cause (i.e., when there are many subjobs, etc).

However, with native docker, it looks like hostname has changed, so now it looks like `Hit failure in taskname (ae1234aa)`.

Is there a different environment variable to use to get this functionality instead? (or can the hostname be customized to include the job name too, like `job-123-ae1234aa` or whatever).

**Comment by orodeh** [comment]
I believe that the `DX_JOB_ID` environment variable holds the job id.

**Comment by jtratner** [comment]
Doesn't look like dxWDL sets any environment variables.  I really just want to ensure the job ID is in the error message (making it much easier to find the actual log), so if dxWDL can do it programmatically, that'd be even better!

Set up:

```
dx mkdir -p /test-env-variable
docker pull centos:7
docker save centos:7 | gzip > centos7.tar.gz
dx upload centos7.tar.gz -o /test-env-variable/centos7.tar.gz
```

and this WDL task:

```
task example_task {
    String example_input
    command <<<
    set -x -o nounset
        env
        echo $DX_JOB_ID
        echo "Last line"
    >>>
    runtime {
        docker: "dx://myproject:/test-env-variable/centos7.tar.gz"
    }
    output {
    }
}
```

Produces the following:

```
2019-04-10 20:52:27 example_task STDERR + docker run --user 0:0 --entrypoint /bin/bash -v /home/dnanexus:/home/dnanexus centos:7 /home/dnanexus/execution/meta/script
2019-04-10 20:52:28 example_task STDERR + env
2019-04-10 20:52:28 example_task STDERR /home/dnanexus/execution/meta/script: line 6: DX_JOB_ID: unbound variable
```

**Comment by jtratner** [comment]
I guess something like this *could* be reasonable?

```
bash -c "source environment; echo '{"error": {"type": "AppError", "message":"Hit failure in taskname ( '${DX_JOB_ID}')"}}' > job_error.json"
```

**Comment by jtratner** [comment]
or even nicer would be to add `--hostname=$DX_JOB_ID` to `docker run` :)
