### ISSUE TITLE
Unhelpful error message when workflow is missing input/output section

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#224]
If you have a workflow that is missing input (or I think output) section, get a weird error:

```
version 1.0
workflow empty_workflow {
}
```

Produces

```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at dxWDL.util.Block$.splitGraph(Block.scala:291)
	at dxWDL.compiler.GenerateIRWorkflow.apply2(GenerateIRWorkflow.scala:636)
	at dxWDL.compiler.GenerateIRWorkflow.apply(GenerateIRWorkflow.scala:663)
```

Would be nice to have it say which file caused it and also say "Workflow is missing input section"

**Comment by orodeh** [comment]
This is a pretty bad error indication, which needs fixing. 

For what it's worth, the real error is that the workflow body is empty. It is fine to have an empty input section.

**Comment by jtratner** [comment]
gotcha!  This was me trying to fuzz dxWDL a bit to figure out why the workflow was failing :)

**Comment by orodeh** [comment]
Fixed in master.
