### ISSUE TITLE
In WDL 1.0, support "stream" as a hash key

### ISSUE THREAD

**Issue by jdidion** [dnanexus/dxWDL#247]
In WDL 1.0, metadata values (in the meta and parameter_meta sections) can be either strings or hashes. Being able to use hashes greatly increases the utility, but it needs to be compatible with setting the "stream" hint. I suggest allowing either of the following:

```wdl
parameter_meta {
  "file": "stream"
}
``` 

```wdl
parameter_meta {
  "file": {
    "stream": true
  }
}
```

**Comment by orodeh** [comment]
Hashes are described in the WDL specification. However, at the moment, Cromwell doesn't support them. Someone would need to add the necessary code.

**Comment by orodeh** [comment]
@jdidion I have open a pull-request against Cromwell/WOM to support JSON-like structures in the meta sections.  

https://github.com/broadinstitute/cromwell/pull/5053

**Comment by orodeh** [comment]
Pull request has been approved.

**Comment by orodeh** [comment]
Release [1.13](https://github.com/dnanexus/dxWDL/releases/tag/1.13) now support json-like meta values. Please give it a spin when you get a chance.
