### ISSUE TITLE
dxWDL complied WDL workflow ends with `Success` even if a task exit with return code > 0

### ISSUE THREAD

**Issue by edmundlth** [dnanexus/dxWDL#272]
@pgarnaut and I was trying to error out a workflow when a QC step reports unsatisfactory quality, but DNAnexus seems to always exit with `Success` state even if a task has a `exit 1` command within it. The workflow was written in WDL and compiled using dxWDL version 1.05. 

Steps to reproduce error: 
 1. The WDL (`test.wdl`) content is as follow: 
```
workflow test_fail_state {
  call just_fail
}

task just_fail {
  command {
    exit 1
  }
}
```
 2. Compile with dxWDL: 
```
java -jar dxWDL-1.05.jar compile test.wdl -project xxxx 
```
 3. Run : `dx run test_fail_state`
This should end with `Success` state with the last few line of `just_fail` stage log file being 
```
success TaskProlog
bash command encapsulation script:
#!/bin/bash
(
    cd /home/dnanexus
    exit 1
) \
  > >( tee /home/dnanexus/meta/stdout ) \
  2> >( tee /home/dnanexus/meta/stderr >&2 )
# make sure the files are on stable storage
# before leaving. This helps with stdin and stdout
# that may be in the fifo queues.
sync
echo $? > /home/dnanexus/meta/rc
Epilog  debugLevel=1
success TaskEpilog
```

@TMiguelT directed me to a line in the [source code](https://github.com/dnanexus/dxWDL/blob/master/src/main/scala/dxWDL/exec/TaskRunner.scala#L266) where he thinks the offending line might be. 

Could you please check if this is intended behaviour?

**Comment by orodeh** [comment]
Fixed on master.

**Comment by orodeh** [comment]
@edmundlth Please try release 1.11, I believe it fixes this problem.
