### ISSUE TITLE
Sometimes dxWDL (or system) appears to move images on archive

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#283]
Currently we keep images in specific locations, to avoid re-uploading them, e.g.:

```
MyProject:/images/package/kind/package-kind-ae123.tar.gz
```

Usually this works just fine, however, sometimes we notice that the images get moved into the `.Applet_archive` folder. Is this a property of dxWDL in some way? Or something about how dxWDL links applets and files?

e.g. if we were building into, say:

```
MyProject:/workflows/jtratner/pkg/
```

we'd see this happen:

```
MyProject:/workflows/jtratner/pkg/.Applet_archive/package-kind-ae123.tar.gz
```

any idea why this happens? Is there any way to prevent it? (I guess otherwise we could build images into a separate project so that the file path hierarchy is preserved)

**Comment by orodeh** [comment]
@jtratner There isn't dxWDL code that does this. If applet X is being moved, I suspect the platform also moves data objects linked to X, in the same project. To avoid this behavior, put the images in a separate project, as you had suggested. This is an inconvenience, I realize. However, it will make sure they aren't touched.

You can check what dxWDL is doing by turning on the verbose flag. Look for lines like:  "Archiving NAME OBJECT_ID". The relevant routine is [here](https://github.com/dnanexus/dxWDL/blob/master/src/main/scala/dxWDL/compiler/DxObjectDirectory.scala#L199). It is called from the Native compilation phase, when the --archive flag is specified. You can read about the compiler passes, for version 1.x, in [Internals.md](https://github.com/dnanexus/dxWDL/blob/master/doc/Internals.md). I suspect you will find it interesting reading, it should also answer some of your questions about a WDL workflow is broken down into pieces.

Please try this with compiler 1.14, and see what it reports.

**Comment by jtratner** [comment]
Yeah makes sense - that's what I figured :)

**Comment by jtratner** [comment]
(I think this now happens because the image tarballs are actually linked to the applets now in way they weren't before?)

**Comment by orodeh** [comment]
Well, I did add links between workflows to applets that they call. This is a step in enabling workflow copying to work. Currently, there is still a missing piece on the platform side for this to work.
