### ISSUE TITLE
Error compiling with example workflows from the Broad 

### ISSUE THREAD

**Issue by ryanrichholt** [dnanexus/dxWDL#291]
Hello, 

I'm trying to compile some of the example workflows shared by the Broad here: 

https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline

and I keep running into the same error. I've tried two different workflows and get the same error message, so maybe I'm doing something wrong?

Heres the commands I used and the error message:

```
$ git clone https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline.git
Cloning into 'five-dollar-genome-analysis-pipeline'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 173 (delta 30), reused 35 (delta 18), pack-reused 120
Receiving objects: 100% (173/173), 102.56 KiB | 2.05 MiB/s, done.
Resolving deltas: 100% (104/104), done.
$ java -jar dxWDL-1.14.jar compile five-dollar-genome-analysis-pipeline/WholeGenomeGermlineSingleSample.wdl --inputs five-dollar-genome-analysis-pipeline/WholeGenomeGermlineSingleSample.hg38.inputs.json --project fastq2bam
dxWDL workflows ignore their parameter meta section
java.lang.Exception: Sanity: cannot find the next callable to compile.
        at dxWDL.compiler.GenerateIR.next$1(GenerateIR.scala:63)
        at dxWDL.compiler.GenerateIR.sortByDependencies(GenerateIR.scala:72)
        at dxWDL.compiler.GenerateIR.apply(GenerateIR.scala:186)
        at dxWDL.compiler.Top.womToIR(Top.scala:254)
        at dxWDL.compiler.Top.apply(Top.scala:308)
        at dxWDL.Main$.compile(Main.scala:431)
        at dxWDL.Main$.dispatchCommand(Main.scala:749)
        at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:806)
        at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at dxWDL.Main$.main(Main.scala:14)
        at dxWDL.Main.main(Main.scala)
```

**Comment by orodeh** [comment]
There is a limitation in the dxWDL compiler, in that it insists on tasks and workflows ending with **exactly** a curly brace, and nothing after that. 
```
}
```

If you have anything else, it will confuse the lexical analysis that excises the tasks and workflows from the original WDL source.

**Comment by ryanrichholt** [comment]
Sorry the wdl that I linked looks like it meets that requirement, am I missing something?
https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/blob/91955c7c242d6f973d525f64cb0a8cf14aac01cb/WholeGenomeGermlineSingleSample.wdl#L219

**Comment by orodeh** [comment]
It

**Comment by orodeh** [comment]
Let me download a and take a look. It isn't just the main entry point, it is also all the imported WDL programs.

**Comment by orodeh** [comment]
You are right. This isn't the problem. I am hunting down the real culprit.

**Comment by orodeh** [comment]
Found the problem. You need to download a setup the auxiliary files. 

```wdl
# Local import
#import "../../../../pipelines/dna_seq/UnmappedBamToAlignedBam.wdl" as ToBam
#import "../../../../tasks/AggregatedBamQC.wdl" as AggregatedQC
#import "../../../../tasks/GermlineVariantDiscovery.wdl" as Calling
#import "../../../../tasks/Qc.wdl" as QC
#import "../../../../tasks/Utilities.wdl" as Utils
#import "../../../../tasks/BamToCram.wdl" as ToCram
#import "../../../../tasks/VariantCalling.wdl" as ToGvcf
#import "../../../../structs/dna_seq/germline/GermlineStructs.wdl"
```

To do so, you need to start by cloning this repository: https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/tree/91955c7c242d6f973d525f64cb0a8cf14aac01cb

You will still need to hunt down `../../../../pipelines/dna_seq/UnmappedBamToAlignedBam.wdl`. 
Once you have all of that, you have a chance of getting it to work.

**Comment by orodeh** [comment]
Leaving this issue open.

**Comment by orodeh** [comment]
I decided to take a look at this again. It turns out that you need to add the following web imports to the `WholeGenomeGermlineSingleSample.wdl` program: 
```
import "https://raw.githubusercontent.com/gatk-workflows/five-dollar-genome-analysis-pipeline/1.2.0/tasks/BamProcessing.wdl"
import "https://raw.githubusercontent.com/gatk-workflows/five-dollar-genome-analysis-pipeline/1.2.0/tasks/Alignment.wdl"
import "https://raw.githubusercontent.com/gatk-workflows/five-dollar-genome-analysis-pipeline/1.2.0/tasks/SplitLargeReadGroup.wdl"
```

Then, we reach a compilation problem in dxWDL itself. Working on that now.

**Comment by ryanrichholt** [comment]
Thank you Ohad. Getting this specific workflow to compile is less important to me than understanding why it failed to compile. It sounds like the import statements inside the imported modules are not working? 


The main file: WholeGenomeGermlineSingleSample.wdl` imports `UnmappedBamToAlignedBam.wdl`

then `UnmappedBamToAlignedBam.wdl` imports the three WDLs you mentioned above: `BamProcessing.wdl`, `Alignment.wdl` and `SplitLargeReadGroup.wdl`. 

So, I could see why adding them the main file would fix the imports, but shouldn't the nested/dependency import work as well?

**Comment by orodeh** [comment]
Well, I think you just found bug :-)

Let's see if I can fix it.

**Comment by orodeh** [comment]
Fixed in master.

**Comment by orodeh** [comment]
Release 1.18 includes the fixes for this. If it doesn't work, I will reopen the ticket. Closing for now.
