### ISSUE TITLE
dxWDL should preferentially pick v2 instance types

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#309]
This WDL file:

```
version 1.0

task hello {
    input {
  String? name
    }
 
  command <<<
    echo 'Hello ${default='World' name}!'
  >>>
  output {
    File response = stdout()
  }
  runtime {
    cpu: 5
   docker: 'ubuntu:latest'
 }
}
```

should (IMO) produce a `hello` applet that uses `mem1_ssd1_v2_x8` instance, but instead you can find that it picks `mem1_ssd1_x8`:

```
  "regionalOptions": {
    "aws:us-east-1": {
      "systemRequirements": {
        "main": {
          "instanceType": "mem1_ssd1_x8"
        }
      }
    }
```

Among various issues, major one is that Instance Type DB incorrectly generates a price list that prioritizes the v1 instances over the v2 (even though they cost the same).

**Comment by orodeh** [comment]
So, `v2` instances should be preferred, if they have same price as a `v1` instance?

**Comment by jtratner** [comment]
Absolutely! The instanceDB seems to think they are more expensive, but they
are definitely the same price.

**Comment by orodeh** [comment]
Fixed in release [v1.31](https://github.com/dnanexus/dxWDL/releases/tag/v1.31)

**Comment by jtratner** [comment]
Awesome - thanks! We will try it out!

**Comment by orodeh** [comment]
I am assuming this has been fixed, so I am closing it. 

Please let me know if this isn't the case, and I will reopen the issue.
