### ISSUE TITLE
Enabling custom reorg causes invalid WDL to be generated

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#335]
Sending you an email with our complex example.

Getting something like this with dxWDL 1.36.1

```
java.lang.Exception: WOM validation errors:
 NonEmptyList(Unrecognized token on line 825, column 12:

    String ___reorg_status = ""
```

**Comment by jtratner** [comment]
Any updates here or ETA on a fix? :)

**Comment by orodeh** [comment]
I believe this is part of release 1.37.

**Comment by orodeh** [comment]
@jtratner, please close this issue if this is now fixed.

**Comment by xquek** [comment]
@jtratner This is realised as part of 1.37 I will close this for now. let me know if you have any other issue thanks!
