### ISSUE TITLE
Warning message for custom reorg should be disableable

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#336]
In dxWDL 1.36.1 the warning message about the custom reorg app is quite aggressive:

1. At a minimum, please provide a `--silence-reorg-warning` flag so that users don't freak out. If I show the current warning message I'm going to get people emailing me every time they attempt to compile.
2. Please hide the "requires CONTRIBUTE" project access message unless the specified applet actually does not have the required level of access for `project`

**Comment by xquek** [comment]
@jtratner , we will only show this message if `--verbosity` is set. Will that work for you 

This will be resolved in #343.

**Comment by orodeh** [comment]
Fixed on master!
