### ISSUE TITLE
Dump a list of applets and containers related to a particular workflow

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#337]
One easy way to test a workflow is to set up some custom inputs for particular tasks and run them in parallel, comparing the results. For example, imagine I had this
<details>
<summary> WDL workflow </summary>

```
workflow w {
}
task demux {}
task align {}
task count_reads {}
```
</details>

Ideally I'd like to be able to define some default inputs files, compile a workflow with dxWDL and then run tests with them.  You might imagine a directory structure with a bunch of input files:

<details>
<summary> Directory structure </summary>

```
inputs/
   demux.input.json
   align.input.json
   count_reads.input.json
wdl/
   my_workflow.wdl
```
</details>

If dxWDL dumped a JSON file that mapped cromwell-style namespaces to WDL tasks, that'd make it really easy to write some tests that look like:

```
dxwdl compile <workflow> -mapping-file mapping.json
dx run $(cat mapping.json | jq -r .tasks.my_workflow.demux.id) -f inputs/demux.input.json
dx run $(cat mapping.json | jq -r .tasks.my_workflow.align.id) -f inputs/demux.input.json
```

and run all of the examples in parallel, shortening the time to discover if anything had failed.

It'd be particularly nice if the mapping file listed out all of the dependencies as well (e.g., linked docker images, platform applets, default inputs, fragments, subworkflows).  This would allow me to write code to, for example, save production workflows to a different location while periodically clearing out non-production workflows.  Ideally the `tasks` section would refer to the actual raw task dxWDL generates, rather than the fragment wrappers.

**Comment by jdidion** [comment]
This is exactly why we created pytest-wdl https://github.com/EliLillyCo/pytest-wdl

**Comment by jtratner** [comment]
Problem (as I understand it) is that pytest WDL requires you to have
Cromwell or miniwdl set up to run vs w dxWDL you don’t have to have
separate infra.

**Comment by jdidion** [comment]
pytest-wdl will soon support dxWDL

**Comment by orodeh** [comment]
@jtratner, I think pytest-wdl is your best bet. @jdidion says it will support dxWDL soon. We don't have the resources to implement this in dxWDL at this time. 

Sorry,
      Ohad.

**Comment by pkaleta** [comment]
>pytest-wdl will soon support dxWDL

@jdidion do you have an estimate of when this is going to be available? Being able to run DX workflows with pytest-wdl would be awesome!

**Comment by orodeh** [comment]
This is now on master (https://github.com/dnanexus/dxWDL/commit/9fa4cc4e81ab62a63f0001c4dfda67e9a5ea0603). 

If you run dxWDL with the `--execTree` command line option, it will output a JSON structure that describes the workflow, and provides all the app/applet/workflow ids.

**Comment by orodeh** [comment]
Released in version https://github.com/dnanexus/dxWDL/releases/tag/v1.42

**Comment by orodeh** [comment]
@jtratner I just re-read the description, and `--execTree` solves some, but not all of this problem. Please try it out and see if it is in the right direction.

**Comment by jtratner** [comment]
@orodeh - I like `execTree` and I think it gets pretty close to what we were looking for here - thanks!
