### ISSUE TITLE
Allow specifying file destination for execTree

### ISSUE THREAD

**Issue by jtratner** [dnanexus/dxWDL#363]
We've set up some automation around `dxwdl` that assumes last line of output will be the executable ID.

I really like the execTree option, but for my purposes it'd be a lot easier if I could specify the JSON be dumped to a file, like this:

```
dxwdl compile <>... -execTree mytree.json
```

so there's no need to futz around figuring out which lines are actually part of valid JSON or not. (otherwise I think that'd end up with a bunch of errors about trying to JSON decode something that happened to be part of verbose output, etc)

Ideally if you specified that argument, dxWDL would go back to printing the executable ID as last line of output.

**Comment by orodeh** [comment]
Very well. Meanwhile, you can it twice, because the second time it will have created all of the platform objects, and will only present the tree. 

```
dxwdl compile foo.wdl
dxwdl compile foo.wdl --execTree
```

**Comment by orodeh** [comment]
@sstadick This is going to be the next step in the colored output mini-project.

**Comment by jtratner** [comment]
yeah that's a good interim solution - thanks!

**Comment by jtratner** [comment]
Aside here @orodeh - right now if you recompile with the exact same arguments, we actually see the workflow be rebuilt by dxWDL, so not actually possible to get this information on a second pass.

Is the guarantee for execTree that it'll always output valid JSON to stdout?  i.e., no chance that something gets printed?

If so, pretty easy to switch to using execTree all the time; just otherwise hard to do it programmatically.

**Comment by orodeh** [comment]
It is true that workflow gets rebuilt. However, if this is the second time, the results will be exactly the same. An applet/workflow is not rebuilt if it already exists, that is guarantied. 

`execTree` will output valid JSON, with no intervening outputs. However, if you also use the `verbose` flags, you well get additional outputs.

**Comment by jtratner** [comment]
My current experience is that rebuilding the same workflow twice in a row
will cause applets to be rebuilt.

Would it be possible to have verbose output dump to stderr?

**Comment by orodeh** [comment]
If you rebuild a workflow twice in a row and the second time applets are rebuilt, then that is a bug. Can you share an example?

**Comment by jtratner** [comment]
@orodeh - I'll try to find one

**Comment by xquek** [comment]
Hi @jtratner , we made a new release of dxWDL today - dxWDL-v1.47.jar. You are now able to get the exectree from workflows compiled with dxWDL-v1.47.jar using the `describe` subcommand so you wont have to recompile the workflow each time. You will also be able to choose between to retrieve the tree in prettyprint and json format

For more information please refer to the [describe option](https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#describe-wdl-workflow-to-obtain-execution-tree) docs.
