### ISSUE TITLE
Add test coverage tracking with Coveralls

### ISSUE THREAD

**Issue by jdidion** [dnanexus/dxWDL#365]
https://coveralls.io/

**Comment by orodeh** [comment]
A while ago I added test coverage. The code is commented out, but you can revive it if you are willing to put in the effort to turn it on by default. Here is the relevant [build.sbt section](https://github.com/dnanexus/dxWDL/blob/master/build.sbt#L112-L120).

**Comment by jdidion** [comment]
Will be done in dxCompiler
