### ISSUE TITLE
support for conditionals, defined() and select_first([ ])

### ISSUE THREAD

**Issue by leepc12** [dnanexus/dxWDL#67]
I am developing a genomic pipeline and it works well with Cromwell.

I tried it with dxWDL but got some compilation errors that complain about conditionals (if), defined() and select_first().

My pipeline looks like.
```
Boolean? flag
call something {
   input : 
       a = if select_first([flag,false]) then 'OKAY' else 'FAIL'
       b = if defined(flag) then 'OKAY' else 'FAIL'
}
```

Also, I have lots of conditionals in a scatter {} block too.
```
scatter( i in range(num_replicate) ) {
    if ( defined(flag) ) {
         call another {
            ......
         }
    }
}
```

Is there any plan to support these functions?

**Comment by orodeh** [comment]
Yes, I am planning to support these functions. The conditionals inside scatters are the furthest away, at the moment. I will take a look at the other cases  (if, defined, select_first), I am curious to see why they don't work.

**Comment by orodeh** [comment]
@leepc12, if you add a comma after the `FAIL`, this should compile much better:

```
Boolean? flag
call something {
   input : 
       a = if select_first([flag,false]) then 'OKAY' else 'FAIL',
       b = if defined(flag) then 'OKAY' else 'FAIL'
}
```

Note that support for optionals isn't perfect yet in dxWDL, I am working on it.

**Comment by orodeh** [comment]
@leepc12 

I simplified your example, and tried it with Cromwell. I am getting an 
[error that I posted to the WDL/Cromwell group](https://gatkforums.broadinstitute.org/wdl/discussion/10775/wdl-workflow-with-optional-input/p1?new=1).

**Comment by leepc12** [comment]
Sorry @orodeh, I found out that `select_first` and `defined` work with dxWDL.

Is an 3-dimensional array supported by dxWDL?
```
Array[Array[Array[File]]] fastqs # fastqs[replicate_id][merge_id][end_id]
```

**Comment by orodeh** [comment]
I haven't tried it myself, but it should definitely work.

**Comment by orodeh** [comment]
This is really an enhancement request, for supporting deep nesting inside scatters and if blocks.
