### ISSUE TITLE
docker run --entrypoint

### ISSUE THREAD

**Issue by dpark01** [dnanexus/dxWDL#71]
Why does dxWDL override the default docker image entrypoint with /bin/bash? Our images rely on a custom default entrypoint to set various environment variables and such, in preparation for execution.

**Comment by orodeh** [comment]
The docker image and its various configuration parameters is tricky. I believe that Cromwell has assumptions on the docker image as well. For example, the entry point has to behave like a shell. 

One way or the other, we can discuss this on the phone on Monday.

**Comment by dpark01** [comment]
I look forward to it.

I'm curious whether your entrypoint override was necessary or solved a particular problem, because from my understanding, it does seem very un-Docker-like to do this without good cause, especially since Docker doesn't really provide any other mechanism to the image-maker to set up environment variables properly. It seems entirely fair to assume that the user has to provide an image that invokes a shell (either in ENTRYPOINT or CMD), especially given that everything inside the WDL's task command section is shell--this shouldn't need to be enforced by the execution host that calls `docker run`.

Google's `dsub` does not override the entrypoint, and neither does Cromwell-on-GCE, Cromwell-on-local, or our pre-WDL implementation ([see this line specifically](https://github.com/dnanexus/viral-ngs/blob/8ec079ec7abfa1698f5526af26ed94f3fd6b8bd5/util/viral-ngs-builder/src/viral-ngs-builder.sh#L13)).

**Comment by orodeh** [comment]
I discussed this over e-mail with Jeff Gentry, and he says that using entrypoints goes against best practices for docker images under WDL. He also thought Cromwell overrides the entry point with `/bin/bash`. Note also, that WDL assumes your entrypoint is *bash-like*. If it isn't strange errors could result. 

Having said this, I can add a compiler flag to *not* override the entrypoint. Let me know what you prefer.

**Comment by dpark01** [comment]
Personally this is no longer an issue for me, in that I've found other ways to set up the environment that do not rely on the entrypoint. So, I no longer care either way.

`dsub` and Cromwell-on-GCE (both of which use the same Google Genomics Pipelines API) do not override the entrypoint, but Cromwell-on-local does.
