### ISSUE TITLE
executing a workflow with empty array gives error

### ISSUE THREAD

**Issue by dpark01** [dnanexus/dxWDL#75]
I have a WDL with a required Array[File] as input, but it is not an Array[File]+, just an Array[File], meaning that it should be perfectly legal for it to be empty...

I'm finding that when I run the resulting compiled dxWDL workflow on DNAnexus, if I fail to supply any inputs to that list when I execute it, I get something like this at runtime:

```
dxWDL.UnboundVariableException: java.lang.RuntimeException: Variable bmtaggerDbs is unboundNov 22, 2017 12:45 PM
	at dxWDL.RunnerEval$.evalDecl$1(RunnerEval.scala:103)
...
Caused by: java.lang.RuntimeException: Variable bmtaggerDbs is unbound
	at dxWDL.UnboundVariableException.<init>(Utils.scala:33)
```

**Comment by orodeh** [comment]
I think I know what the root cause is. I will fix it.

**Comment by orodeh** [comment]
@dpark01, I believe release 0.52 fixes this problem. Please give it a try, and let me know if the problem persists.

**Comment by dpark01** [comment]
Okay, so now when I do this, it appears to work: it compiles to a dx workflow where the multi-file inputs are rendered as optional, not required, and I'm trying an execution now with empty input, and it seems to work so far.

But I noticed an interesting new behavior that doesn't seem right that might be related to the work done on this issue. I'll log it separately as a new issue.
