### ISSUE TITLE
Array[File]+ is compiled to an optional array input

### ISSUE THREAD

**Issue by dpark01** [dnanexus/dxWDL#78]
If I specify a task input in WDL as `Array[File]+`, dxWDL creates a DNAnexus workflow that calls this an optional array input, and it lacks the orange box in the web UI. I can provide an example if you're unable to reproduce this.

**Comment by orodeh** [comment]
Nice find. To my knowledge, you are the first person to use the `+` flag 👍 

This has been fixed in the development release, which I hope to release soon.

**Comment by orodeh** [comment]
@dpark01, I believe release 0.52 fixes this problem. Please give it a try, and let me know if the problem persists.

**Comment by dpark01** [comment]
Yep this looks fixed
