### ISSUE TITLE
0.53: all optional inputs are gone

### ISSUE THREAD

**Issue by dpark01** [dnanexus/dxWDL#81]
All optional inputs have disappeared from the compiled outputs of dxWDL.

This appears to be true for both CLI and Web UI, so I don't think it has anything to do with that. But all input parameters with `?` in WDL are gone (regardless of whether it was an Array, a single, a File, Integer, or String).

Possibly inadvertent side effect of the fix to #75?

**Comment by orodeh** [comment]
I can reproduce this problem easily in the UI, but optionals work fine for me on the CLI. Can you please share an example WDL file where this happens?

**Comment by dpark01** [comment]
The aforementioned workflow-F8QFVfj0xf5q97FfF0zK0Jgg is a good example. Interestingly enough, this is another place where `dx run --help` + `dx describe` vs `dx describe --json`. Only the json format shows some of the optional parameters, some of which include:
 - stage_4.novocraft_license (File?)
 - stage_4.refine1_novoalign_options (String?)

Whereas the `dx describe` and `dx run --help` do not show these.

**Comment by orodeh** [comment]
The problem is that the workflow is *locked down*. This means that it allows access only to workflow level inputs, you cannot access stage inputs, and they are hidden in the UI.

I will see what can be done.

**Comment by orodeh** [comment]
This should work the way it used to, when compiling to regular workflows. This is in progress.
