### ISSUE TITLE
write_lines doesn't work with docker

### ISSUE THREAD

**Issue by mlin** [dnanexus/dxWDL#90]
```
task write_lines_bug {
    Array[File] files

    command <<<
        filenames=${write_lines(files)}
        echo "Contents of $filenames:"
        cat $filenames
    >>>

    runtime {
        docker: "ubuntu:16.04"
    }
}
```

```
dx run write_lines_bug -i files="ENCODE Reference Files:/bed12.as" -i files="ENCODE Reference Files:/broadPeak.as" -y --watch
```

```
cat: /tmp/dxWDL_Runner/job_scratch_space/wdlarray-f076c962b319564fd923ee2c21d3e17a.tmp: No such file or directory
```

dxWDL's version of the `write_lines` stdlib function writes the temporary file to `/tmp/dxWDL_Runner/job_scratch_space/wdlarray-xxxx.tmp` on the platform worker. But this doesn't seem to be mounted inside the docker container, so the command is unable to access it. Probably we need to mount that temp directory, or change the temp directory location into something that is already mounted.

There are two generalizations to bear in mind. 

1. Other WDL stdlib functions also write out temporary files that will need to be accessible to the command
2. There are also `read_lines` and other analogous functions, do these work with docker?

**Comment by orodeh** [comment]
Thanks, fixed by moving the temporary directory under the users's home directory.
