### ISSUE TITLE
reduce default logging verbosity

### ISSUE THREAD

**Issue by mlin** [dnanexus/dxWDL#91]
The dxWDL runtime prints a lot of extra information into the job log, which has probably been useful for dev/debugging but as you approach 1.0 and users start to run larger-scale jobs, it would be good to reduce the verbosity somewhat at least on default settings.

For example it always does a `ls -lR` before and after which becomes really unwieldy if the command ends up creating a lot of intermediate files, and prints the whole script.

**Comment by orodeh** [comment]
Improved in version 0.65.
